name: Docker

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Image Tag
        id: date
        run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build . \
          --file Dockerfile \
          --tag $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{ steps.date.outputs.date }}

      - name: Push Docker Image
        run: |
          docker push $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{ steps.date.outputs.date }}

      - name: Run Container
        run: |
          docker run -d \
          --name test-container \
          -p 4000:4000 \
          $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{ steps.date.outputs.date }}

      - name: Verify Container Running
        run: |
          docker ps

      - name: Test Application
        run: |
         sleep 10
         curl http://localhost:4000